gui:
  tabWidth: 2
  border: rounded

  theme:
    activeBorderColor:
      - '#61afef'
      - bold

    inactiveBorderColor:
      - '#979eab'

    searchingActiveBorderColor:
      - '#e5c07b'

    optionsTextColor:
      - '#979eab'

    selectedLineBgColor:
      - '#3e4452'

    cherryPickedCommitBgColor:
      - '#61afef'

    markedBaseCommitBgColor:
      - '#e5c07b'

    unstagedChangesColor:
      - '#e06c75'

    defaultFgColor:
      - '#abb2bf'
